NATS connection updates, Added Sample Intake Message handler
n1zea144/cmo-metadb pull request #1
Opened 2020-12-04 23:08 UTC by ao508

Signed-off-by: Angelica Ochoa <ochoaa@mskcc.org>

2020-12-09 20:09 UTC, n1zea144 requested changes

2020-12-09 20:09 UTC, n1zea144 commented on service/src/main/java/org/mskcc/cmo/metadb/service/MetadbApp.java
> +package org.mskcc.cmo.metadb.service;
Are we going to consolidate this with MetadbMessagingApp.java  ?  I also think we should move this "bootstrap" class up one level.

2020-12-09 20:09 UTC, n1zea144 commented on service/src/main/java/org/mskcc/cmo/metadb/service/consumer/SampleIntakeMessageConsumer.java
> +        System.out.printf("*** Message received on igo.new-sample-intake topic ***\n");
I would remove these logging statements or use a proper logger (or publish them to a logging topic).

2020-12-09 21:19 UTC, ao508 commented on service/src/main/java/org/mskcc/cmo/metadb/service/MetadbApp.java
> +package org.mskcc.cmo.metadb.service;
not consolidating, will be removing MetadbMessagingApp.java

2020-12-10 17:56 UTC, n1zea144 approved these changes

2020-12-10 17:56 UTC, merged